In [14]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.9

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.48497343084992534
Change in weights for hidden layer to output layer:
[0.01447285 0.01000653]
Change in weights for input layer to hidden layer:
[[ 3.18609984e-04 -9.20121311e-04]
 [ 6.37219968e-05 -1.84024262e-04]
 [-1.27443994e-04  3.68048524e-04]]


In [15]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.48797532522445153
Change in weights for hidden layer to output layer:
[0.01410092 0.00974525]
Change in weights for input layer to hidden layer:
[[ 3.55311011e-04 -8.66392198e-04]
 [ 7.10622022e-05 -1.73278440e-04]
 [-1.42124404e-04  3.46556879e-04]]


In [16]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.49090012278942086
Change in weights for hidden layer to output layer:
[0.01373745 0.00949014]
Change in weights for input layer to hidden layer:
[[ 3.88745543e-04 -8.15522619e-04]
 [ 7.77491085e-05 -1.63104524e-04]
 [-1.55498217e-04  3.26209048e-04]]


In [17]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.49374947907837463
Change in weights for hidden layer to output layer:
[0.01338238 0.00924113]
Change in weights for input layer to hidden layer:
[[ 4.19105024e-04 -7.67377779e-04]
 [ 8.38210048e-05 -1.53475556e-04]
 [-1.67642010e-04  3.06951111e-04]]


In [18]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.49652505183765094
Change in weights for hidden layer to output layer:
[0.01303565 0.00899815]
Change in weights for input layer to hidden layer:
[[ 4.46573000e-04 -7.21827327e-04]
 [ 8.93146000e-05 -1.44365465e-04]
 [-1.78629200e-04  2.88730931e-04]]


In [19]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.4992284965783836
Change in weights for hidden layer to output layer:
[0.01269715 0.00876114]
Change in weights for input layer to hidden layer:
[[ 4.71325110e-04 -6.78745462e-04]
 [ 9.42650221e-05 -1.35749092e-04]
 [-1.88530044e-04  2.71498185e-04]]


In [20]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5018614625960562
Change in weights for hidden layer to output layer:
[0.0123668  0.00852999]
Change in weights for input layer to hidden layer:
[[ 4.93529138e-04 -6.38010989e-04]
 [ 9.87058276e-05 -1.27602198e-04]
 [-1.97411655e-04  2.55204396e-04]]


In [21]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5044255894239168
Change in weights for hidden layer to output layer:
[0.01204447 0.00830464]
Change in weights for input layer to hidden layer:
[[ 0.00051335 -0.00059951]
 [ 0.00010267 -0.0001199 ]
 [-0.00020534  0.0002398 ]]


In [22]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5069225036878405
Change in weights for hidden layer to output layer:
[0.01173007 0.00808498]
Change in weights for input layer to hidden layer:
[[ 0.00053093 -0.00056312]
 [ 0.00010619 -0.00011262]
 [-0.00021237  0.00022525]]


In [23]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5093538163316368
Change in weights for hidden layer to output layer:
[0.01142345 0.00787091]
Change in weights for input layer to hidden layer:
[[ 0.00054641 -0.00052875]
 [ 0.00010928 -0.00010575]
 [-0.00021857  0.0002115 ]]


In [24]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.511721120183295
Change in weights for hidden layer to output layer:
[0.0111245  0.00766233]
Change in weights for input layer to hidden layer:
[[ 5.59951215e-04 -4.96284850e-04]
 [ 1.11990243e-04 -9.92569699e-05]
 [-2.23980486e-04  1.98513940e-04]]


In [25]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5140259878342245
Change in weights for hidden layer to output layer:
[0.01083308 0.00745914]
Change in weights for input layer to hidden layer:
[[ 5.71664928e-04 -4.65630676e-04]
 [ 1.14332986e-04 -9.31261351e-05]
 [-2.28665971e-04  1.86252270e-04]]


In [26]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.516269969805121
Change in weights for hidden layer to output layer:
[0.01054905 0.00726122]
Change in weights for input layer to hidden layer:
[[ 5.81679687e-04 -4.36692833e-04]
 [ 1.16335937e-04 -8.73385667e-05]
 [-2.32671875e-04  1.74677133e-04]]


In [27]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5184545929736806
Change in weights for hidden layer to output layer:
[0.01027226 0.00706848]
Change in weights for input layer to hidden layer:
[[ 5.90112538e-04 -4.09381572e-04]
 [ 1.18022508e-04 -8.18763144e-05]
 [-2.36045015e-04  1.63752629e-04]]


In [29]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.520581359240952
Change in weights for hidden layer to output layer:
[0.01000258 0.0068808 ]
Change in weights for input layer to hidden layer:
[[ 5.97074139e-04 -3.83611281e-04]
 [ 1.19414828e-04 -7.67222563e-05]
 [-2.38829656e-04  1.53444513e-04]]


In [30]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

output : 0.5226517444146495
Change in weights for hidden layer to output layer:
[0.00973986 0.00669808]
Change in weights for input layer to hidden layer:
[[ 6.02669007e-04 -3.59300371e-04]
 [ 1.20533801e-04 -7.18600743e-05]
 [-2.41067603e-04  1.43720149e-04]]
