In [69]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.9

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
print("hidden layer input: {}".format(hidden_layer_output))
print("hidden layer output: {}".format(hidden_layer_output))
print("output layer in: {}".format(output_layer_in))


output = sigmoid(output_layer_in)
print('output : {}'.format(output))
## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)


# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

print("output error term: {}".format(output_error_term))
print("weights hidden output: {}".format(weights_hidden_output))
print("weights input hidden: {}".format(weights_input_hidden))


    
# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

weights_input_hidden += delta_w_i_h
weights_hidden_output += delta_w_h_o

print("weights hidden output: {}".format(weights_hidden_output))
print("weights input hidden: {}".format(weights_input_hidden))



hidden layer input: [0.55971365 0.38698582]
hidden layer output: [0.55971365 0.38698582]
output layer in: -0.06012438223148006
output : 0.48497343084992534
output error term: 0.028730669543515018
weights hidden output: [ 0.1 -0.3]
weights input hidden: [[ 0.5 -0.6]
 [ 0.1 -0.2]
 [ 0.1  0.7]]
Change in weights for hidden layer to output layer:
[0.01447285 0.01000653]
Change in weights for input layer to hidden layer:
[[ 3.18609984e-04 -9.20121311e-04]
 [ 6.37219968e-05 -1.84024262e-04]
 [-1.27443994e-04  3.68048524e-04]]
weights hidden output: [ 0.11447285 -0.28999347]
weights input hidden: [[ 0.50031861 -0.60092012]
 [ 0.10006372 -0.20018402]
 [ 0.09987256  0.70036805]]


In [70]:
## Forward pass

def train(x,weights_input_hidden,weights_hidden_output):
    hidden_layer_input = np.dot(x, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    
    print("hidden layer input: {}".format(hidden_layer_input))
    print("hidden layer output: {}".format(hidden_layer_output))
    print("weights input hidden: {}".format(weights_input_hidden))
    print("weights hidden output: {}".format(weights_hidden_output))

    output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
    
    print("output layer in: {}".format(output_layer_in))

    output = sigmoid(output_layer_in)
    
    print('output : {}'.format(output))
    ## Backwards pass
    ## TODO: Calculate output error
    error = target - output

    # TODO: Calculate error term for output layer
    output_error_term = error * output * (1 - output)

    print("output error term: {}".format(output_error_term))
    print("weights hidden output: {}".format(weights_hidden_output))
    print("hidden layer output: {}".format(hidden_layer_output))

    # TODO: Calculate error term for hidden layer
    hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                        hidden_layer_output * (1 - hidden_layer_output)

    # TODO: Calculate change in weights for hidden layer to output layer
    delta_w_h_o = learnrate * output_error_term * hidden_layer_output

    # TODO: Calculate change in weights for input layer to hidden layer
    delta_w_i_h = learnrate * hidden_error_term * x[:, None]

    print('Change in weights for hidden layer to output layer:')
    print(delta_w_h_o)
    print('Change in weights for input layer to hidden layer:')
    print(delta_w_i_h)

    weights_input_hidden += delta_w_i_h
    weights_hidden_output += delta_w_h_o
    
    return weights_input_hidden, weights_hidden_output

In [73]:
epoch = 1000

print("before loop")
print("w i h {}\n w h o {}".format(weights_input_hidden,weights_hidden_output))

for t in range(epoch):
    print("inside loop")
    weights_input_hidden,weights_hidden_output = train(x,weights_input_hidden,weights_hidden_output)

before loop
w i h [[ 0.54027606 -0.61363167]
 [ 0.10805521 -0.20272633]
 [ 0.08388958  0.70545267]]
 w h o [0.61840752 0.05571286]
inside loop
hidden layer input: [ 0.26416564 -0.468179  ]
hidden layer output: [0.56566002 0.38504734]
weights input hidden: [[ 0.54027606 -0.61363167]
 [ 0.10805521 -0.20272633]
 [ 0.08388958  0.70545267]]
weights hidden output: [0.61840752 0.05571286]
output layer in: 0.3712605007813796
output : 0.591763524711178
output error term: 0.0019897632157811736
weights hidden output: [0.61840752 0.05571286]
hidden layer output: [0.56566002 0.38504734]
Change in weights for hidden layer to output layer:
[0.00101298 0.00068954]
Change in weights for input layer to hidden layer:
[[ 1.36042300e-04  1.18120482e-05]
 [ 2.72084600e-05  2.36240963e-06]
 [-5.44169200e-05 -4.72481927e-06]]
inside loop
hidden layer input: [ 0.26424726 -0.46817191]
hidden layer output: [0.56568007 0.38504902]
weights input hidden: [[ 0.5404121  -0.61361986]
 [ 0.10808242 -0.20272397]
 [ 0.08

hidden layer input: [ 0.26694844 -0.4678961 ]
hidden layer output: [0.5663436  0.38511433]
weights input hidden: [[ 0.54491407 -0.61316017]
 [ 0.10898281 -0.20263203]
 [ 0.08203437  0.70526407]]
weights hidden output: [0.65206922 0.07861491]
output layer in: 0.39957095651391755
output : 0.5985845734412881
output error term: 0.00034010022484811883
weights hidden output: [0.65206922 0.07861491]
hidden layer output: [0.5663436  0.38511433]
Change in weights for hidden layer to output layer:
[0.00017335 0.00011788]
Change in weights for input layer to hidden layer:
[[ 2.45097505e-05  2.84910462e-06]
 [ 4.90195011e-06  5.69820924e-07]
 [-9.80390022e-06 -1.13964185e-06]]
inside loop
hidden layer input: [ 0.26696315 -0.4678944 ]
hidden layer output: [0.56634721 0.38511473]
weights input hidden: [[ 0.54493858 -0.61315733]
 [ 0.10898772 -0.20263147]
 [ 0.08202457  0.70526293]]
weights hidden output: [0.65224257 0.07873279]
output layer in: 0.3997169182044231
output : 0.5986196447694723
output e

output layer in: 0.4034591347161457
output : 0.5995184699537397
output error term: 0.0001156134736866151
weights hidden output: [0.65668632 0.08175433]
hidden layer output: [0.56644011 0.38512532]
Change in weights for hidden layer to output layer:
[5.89392982e-05 4.00731083e-05]
Change in weights for input layer to hidden layer:
[[ 8.39038769e-06  1.00721083e-06]
 [ 1.67807754e-06  2.01442165e-07]
 [-3.35615508e-06 -4.02884331e-07]]
inside loop
hidden layer input: [ 0.26734646 -0.46784909]
hidden layer output: [0.56644135 0.38512546]
weights input hidden: [[ 0.54557744 -0.61308181]
 [ 0.10911549 -0.20261636]
 [ 0.08176903  0.70523273]]
weights hidden output: [0.65674526 0.0817944 ]
output layer in: 0.40350877713012556
output : 0.5995303888435611
output error term: 0.00011275068090744613
weights hidden output: [0.65674526 0.0817944 ]
hidden layer output: [0.56644135 0.38512546]
Change in weights for hidden layer to output layer:
[5.74799831e-05 3.90808422e-05]
Change in weights for inp

weights hidden output: [0.65831567 0.0828621 ]
output layer in: 0.40483155256306025
output : 0.5998479370402283
output error term: 3.6499731457771486e-05
weights hidden output: [0.65831567 0.0828621 ]
hidden layer output: [0.56647433 0.3851293 ]
Change in weights for hidden layer to output layer:
[1.86085449e-05 1.26514045e-05]
Change in weights for input layer to hidden layer:
[[ 2.65540904e-06  3.22291228e-07]
 [ 5.31081807e-07  6.44582456e-08]
 [-1.06216361e-06 -1.28916491e-07]]
inside loop
hidden layer input: [ 0.26748235 -0.46783268]
hidden layer output: [0.56647472 0.38512935]
weights input hidden: [[ 0.54580392 -0.61305447]
 [ 0.10916078 -0.20261089]
 [ 0.08167843  0.70522179]]
weights hidden output: [0.65833428 0.08287475]
output layer in: 0.40484722763474557
output : 0.599851699527901
output error term: 3.559650864819221e-05
weights hidden output: [0.65833428 0.08287475]
hidden layer output: [0.56647472 0.38512935]
Change in weights for hidden layer to output layer:
[1.8148070

weights hidden output: [0.65887334 0.08324124]
output layer in: 0.4053013203223776
output : 0.599960690287654
output error term: 9.43463995299417e-06
weights hidden output: [0.65887334 0.08324124]
hidden layer output: [0.56648606 0.38513068]
Change in weights for hidden layer to output layer:
[4.81013283e-06 3.27021234e-06]
Change in weights for input layer to hidden layer:
[[ 6.86960989e-07  8.36887992e-08]
 [ 1.37392198e-07  1.67377598e-08]
 [-2.74784396e-07 -3.34755197e-08]]
inside loop
hidden layer input: [ 0.26752894 -0.46782702]
hidden layer output: [0.56648616 0.38513069]
weights input hidden: [[ 0.54588156 -0.61304503]
 [ 0.10917631 -0.20260901]
 [ 0.08164737  0.70521801]]
weights hidden output: [0.65887815 0.08324451]
output layer in: 0.4053053723375777
output : 0.5999616628027585
output error term: 9.201221229739477e-06
weights hidden output: [0.65887815 0.08324451]
hidden layer output: [0.56648616 0.38513069]
Change in weights for hidden layer to output layer:
[4.69112806e-0

Change in weights for hidden layer to output layer:
[1.48191018e-06 1.00748588e-06]
Change in weights for input layer to hidden layer:
[[ 2.11681408e-07  2.58111309e-08]
 [ 4.23362817e-08  5.16222618e-09]
 [-8.46725634e-08 -1.03244524e-08]]
inside loop
hidden layer input: [ 0.26754018 -0.46782565]
hidden layer output: [0.56648892 0.38513101]
weights input hidden: [[ 0.5459003  -0.61304275]
 [ 0.10918006 -0.20260855]
 [ 0.08163988  0.7052171 ]]
weights hidden output: [0.65900935 0.08333371]
output layer in: 0.40541589511263026
output : 0.5999881888229478
output error term: 2.8347103916559104e-06
weights hidden output: [0.65900935 0.08333371]
hidden layer output: [0.56648892 0.38513101]
Change in weights for hidden layer to output layer:
[1.44524884e-06 9.82561395e-07]
Change in weights for input layer to hidden layer:
[[ 2.06445019e-07  2.51728859e-08]
 [ 4.12890038e-08  5.03457719e-09]
 [-8.25780075e-08 -1.00691544e-08]]
inside loop
hidden layer input: [ 0.26754031 -0.46782563]
hidden 

Change in weights for hidden layer to output layer:
[6.16666980e-07 4.19244444e-07]
Change in weights for input layer to hidden layer:
[[ 8.80914666e-08  1.07438323e-08]
 [ 1.76182933e-08  2.14876646e-09]
 [-3.52365866e-08 -4.29753291e-09]]
inside loop
hidden layer input: [ 0.26754311 -0.46782529]
hidden layer output: [0.56648964 0.3851311 ]
weights input hidden: [[ 0.54590518 -0.61304215]
 [ 0.10918104 -0.20260843]
 [ 0.08163793  0.70521686]]
weights hidden output: [0.65904346 0.0833569 ]
output layer in: 0.40544462895736044
output : 0.5999950849937417
output error term: 1.1796063333357114e-06
weights hidden output: [0.65904346 0.0833569 ]
hidden layer output: [0.56648964 0.3851311 ]
Change in weights for hidden layer to output layer:
[6.01411292e-07 4.08872773e-07]
Change in weights for input layer to hidden layer:
[[ 8.59122548e-08  1.04780937e-08]
 [ 1.71824510e-08  2.09561875e-09]
 [-3.43649019e-08 -4.19123749e-09]]
inside loop
hidden layer input: [ 0.26754316 -0.46782528]
hidden 

Change in weights for hidden layer to output layer:
[3.29665422e-07 2.24124773e-07]
Change in weights for input layer to hidden layer:
[[ 4.70938225e-08  5.74411119e-09]
 [ 9.41876450e-09  1.14882224e-09]
 [-1.88375290e-08 -2.29764448e-09]]
inside loop
hidden layer input: [ 0.26754408 -0.46782517]
hidden layer output: [0.56648988 0.38513113]
weights input hidden: [[ 0.54590679 -0.61304195]
 [ 0.10918136 -0.20260839]
 [ 0.08163728  0.70521678]]
weights hidden output: [0.65905478 0.08336459]
output layer in: 0.4054541600839108
output : 0.5999973724713025
output error term: 6.306082681650677e-07
weights hidden output: [0.65905478 0.08336459]
hidden layer output: [0.56648988 0.38513113]
Change in weights for hidden layer to output layer:
[3.21509882e-07 2.18580185e-07]
Change in weights for input layer to hidden layer:
[[ 4.59287983e-08  5.60202355e-09]
 [ 9.18575965e-09  1.12040471e-09]
 [-1.83715193e-08 -2.24080942e-09]]
inside loop
hidden layer input: [ 0.2675441  -0.46782517]
hidden la

Change in weights for hidden layer to output layer:
[1.47891647e-07 1.00544892e-07]
Change in weights for input layer to hidden layer:
[[ 2.11270508e-08  2.57702718e-09]
 [ 4.22541017e-09  5.15405435e-10]
 [-8.45082034e-09 -1.03081087e-09]]
inside loop
hidden layer input: [ 0.26754469 -0.4678251 ]
hidden layer output: [0.56649003 0.38513114]
weights input hidden: [[ 0.54590782 -0.61304183]
 [ 0.10918156 -0.20260837]
 [ 0.08163687  0.70521673]]
weights hidden output: [0.65906194 0.08336946]
output layer in: 0.4054601966924143
output : 0.5999988212596411
output error term: 2.828979640143413e-07
weights hidden output: [0.65906194 0.08336946]
hidden layer output: [0.56649003 0.38513114]
Change in weights for hidden layer to output layer:
[1.44232989e-07 9.80575346e-08]
Change in weights for input layer to hidden layer:
[[ 2.06043980e-08  2.51327770e-09]
 [ 4.12087960e-09  5.02655540e-10]
 [-8.24175920e-09 -1.00531108e-09]]
inside loop
hidden layer input: [ 0.2675447 -0.4678251]
hidden laye

Change in weights for hidden layer to output layer:
[2.62597507e-08 1.78528231e-08]
Change in weights for input layer to hidden layer:
[[ 3.75136195e-09  4.57597129e-10]
 [ 7.50272389e-10  9.15194258e-11]
 [-1.50054478e-09 -1.83038852e-10]]
inside loop
hidden layer input: [ 0.2675451  -0.46782505]
hidden layer output: [0.56649013 0.38513115]
weights input hidden: [[ 0.5459085  -0.61304175]
 [ 0.1091817  -0.20260835]
 [ 0.0816366   0.7052167 ]]
weights hidden output: [0.65906674 0.08337272]
output layer in: 0.4054642360325919
output : 0.5999997907018444
output error term: 5.0231566101431133e-08
weights hidden output: [0.65906674 0.08337272]
hidden layer output: [0.56649013 0.38513115]
Change in weights for hidden layer to output layer:
[2.56101178e-08 1.74111669e-08]
Change in weights for input layer to hidden layer:
[[ 3.65855816e-09  4.46276852e-10]
 [ 7.31711631e-10  8.92553705e-11]
 [-1.46342326e-09 -1.78510741e-10]]
inside loop
hidden layer input: [ 0.2675451  -0.46782505]
hidden l

Change in weights for hidden layer to output layer:
[9.17005034e-09 6.23430454e-09]
Change in weights for input layer to hidden layer:
[[ 1.30999769e-09  1.59796347e-10]
 [ 2.61999538e-10  3.19592694e-11]
 [-5.23999075e-10 -6.39185388e-11]]
inside loop
hidden layer input: [ 0.26754516 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.5459086  -0.61304173]
 [ 0.10918172 -0.20260835]
 [ 0.08163656  0.70521669]]
weights hidden output: [0.65906741 0.08337318]
output layer in: 0.40546480357450043
output : 0.5999999269119184
output error term: 1.7541140649229823e-08
weights hidden output: [0.65906741 0.08337318]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[8.94319499e-09 6.08007580e-09]
Change in weights for input layer to hidden layer:
[[ 1.27759003e-09  1.55843201e-10]
 [ 2.55518007e-10  3.11686402e-11]
 [-5.11036014e-10 -6.23372804e-11]]
inside loop
hidden layer input: [ 0.26754516 -0.46782504]
hidden 

hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590863 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163655  0.70521669]]
weights hidden output: [0.65906767 0.08337336]
output layer in: 0.4054650253279899
output : 0.599999980132758
output error term: 4.76813814998438e-09
weights hidden output: [0.65906767 0.08337336]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.43099297e-09 1.65272271e-09]
Change in weights for input layer to hidden layer:
[[ 3.47282330e-10  4.23623254e-11]
 [ 6.94564660e-11  8.47246508e-12]
 [-1.38912932e-10 -1.69449302e-11]]
inside loop
hidden layer input: [ 0.26754518 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590864 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163655  0.70521669]]
weights hidden output: [0.65906768 0.08337336]
output layer in: 0.4054650273758656
output : 0.5999999806242482
output error term: 4.650180502474127e-09
weights h

Change in weights for hidden layer to output layer:
[8.70450221e-10 5.91779926e-10]
Change in weights for input layer to hidden layer:
[[ 1.24349191e-10  1.51684167e-11]
 [ 2.48698382e-11  3.03368334e-12]
 [-4.97396763e-11 -6.06736668e-12]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590864 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906774 0.0833734 ]
output layer in: 0.4054650792008621
output : 0.5999999930622475
output error term: 1.6650606056942282e-09
weights hidden output: [0.65906774 0.0833734 ]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[8.48916393e-10 5.77140046e-10]
Change in weights for input layer to hidden layer:
[[ 1.21272951e-10  1.47931695e-11]
 [ 2.42545901e-11  2.95863390e-12]
 [-4.85091803e-11 -5.91726781e-12]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden l

output layer in: 0.40546509666664027
output : 0.5999999972540342
output error term: 6.59031790648906e-10
weights hidden output: [0.65906776 0.08337342]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[3.36001518e-10 2.28432309e-10]
Change in weights for input layer to hidden layer:
[[ 4.79998939e-11  5.85514462e-12]
 [ 9.59997877e-12  1.17102892e-12]
 [-1.91999575e-11 -2.34205785e-12]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906776 0.08337342]
output layer in: 0.40546509694968896
output : 0.599999997321966
output error term: 6.427281654585932e-10
weights hidden output: [0.65906776 0.08337342]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[3.27689259e-10 2.22781178e-10]
Change in weights for input

weights hidden output: [0.65906777 0.08337342]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[1.54558075e-10 1.05077079e-10]
Change in weights for input layer to hidden layer:
[[ 2.20795767e-11  2.69332098e-12]
 [ 4.41591535e-12  5.38664196e-13]
 [-8.83183069e-12 -1.07732839e-12]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337342]
output layer in: 0.40546510297535293
output : 0.5999999987681253
output error term: 2.956499315069597e-10
weights hidden output: [0.65906777 0.08337342]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[1.50734498e-10 1.02477600e-10]
Change in weights for input layer to hidden layer:
[[ 2.15333550e-11  2.62669151e-12]
 [ 4.30667100e-12  5.25338303e-13]
 [-8.61334

 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.40546510556284193
output : 0.5999999993891226
output error term: 1.4661056376399864e-10
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[7.47480967e-11 5.08178665e-11]
Change in weights for input layer to hidden layer:
[[ 1.06782278e-11  1.30255648e-12]
 [ 2.13564557e-12  2.60511295e-13]
 [-4.27129113e-12 -5.21022591e-13]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.40546510562581
output : 0.599999999404235
output error term: 1.429835983656642e-10
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to

hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651073433608
output : 0.5999999998164471
output error term: 4.4052681509387065e-11
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.24598693e-11 1.52694542e-11]
Change in weights for input layer to hidden layer:
[[ 3.20853122e-12  3.91384530e-13]
 [ 6.41706245e-13  7.82769061e-14]
 [-1.28341249e-12 -1.56553812e-13]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651073622811
output : 0.5999999998209881
o

hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[5.95413804e-12 4.04795046e-12]
Change in weights for input layer to hidden layer:
[[ 8.50585442e-13  1.03756505e-13]
 [ 1.70117088e-13  2.07513010e-14]
 [-3.40234177e-13 -4.15026019e-14]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.40546510791042967
output : 0.5999999999525436
output error term: 1.1389529320122387e-11
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[5.80685059e-12 3.94781635e-12]
Change in weights for input layer to hidden layer:
[[ 8.29544519e-13  1.01189881e-13]
 [ 1.65908904e-13  2.02379762e-14]
 [-3.31817807e-13 -4.04759525e-14]]
inside loop
hidden l

Change in weights for hidden layer to output layer:
[2.24149440e-12 1.52389115e-12]
Change in weights for input layer to hidden layer:
[[ 3.20211338e-13  3.90601668e-14]
 [ 6.40422675e-14  7.81203335e-15]
 [-1.28084535e-13 -1.56240667e-14]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651080337251
output : 0.5999999999821346
output error term: 4.287690202950386e-12
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.18604085e-12 1.48619078e-12]
Change in weights for input layer to hidden layer:
[[ 3.12289455e-13  3.80938361e-14]
 [ 6.24578910e-14  7.61876721e-15]
 [-1.24915782e-13 -1.52375344e-14]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden la

weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651080815103
output : 0.599999999993603
output error term: 1.5352785709492298e-12
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[7.82748174e-13 5.32155251e-13]
Change in weights for input layer to hidden layer:
[[ 1.11820417e-13  1.36401296e-14]
 [ 2.23640835e-14  2.72802593e-15]
 [-4.47281670e-14 -5.45605185e-15]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.40546510808216973
output : 0.5999999999937613
output error term: 1.4972822981540582e-12
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[7.6337611

Change in weights for hidden layer to output layer:
[2.35181735e-13 1.59889476e-13]
Change in weights for input layer to hidden layer:
[[ 3.35971653e-14  4.09826488e-15]
 [ 6.71943306e-15  8.19652977e-16]
 [-1.34388661e-14 -1.63930595e-15]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651081003536
output : 0.5999999999981254
output error term: 4.4990677849980123e-13
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.29380984e-13 1.55945806e-13]
Change in weights for input layer to hidden layer:
[[ 3.27684922e-14  3.99718129e-15]
 [ 6.55369843e-15  7.99436259e-16]
 [-1.31073969e-14 -1.59887252e-15]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden l

weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[7.24618400e-14 4.92635435e-14]
Change in weights for input layer to hidden layer:
[[ 1.03516220e-14  1.26271632e-15]
 [ 2.07032440e-15  2.52543263e-16]
 [-4.14064879e-15 -5.05086527e-16]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651081057579
output : 0.5999999999994224
output error term: 1.3860912417846826e-13
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[7.06686336e-14 4.80444232e-14]
Change in weights for input layer to hidden layer:
[[ 1.00954514e-14  1.23146799e-15]
 [ 2.01909027e-15  2.46293599e-16]
 [-4.03818

weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.40588524e-14 1.63565308e-14]
Change in weights for input layer to hidden layer:
[[ 3.43695585e-15  4.19248331e-16]
 [ 6.87391171e-16  8.38496662e-17]
 [-1.37478234e-15 -1.67699332e-16]]
inside loop
hidden layer input: [ 0.26754519 -0.46782504]
hidden layer output: [0.56649015 0.38513116]
weights input hidden: [[ 0.54590865 -0.61304173]
 [ 0.10918173 -0.20260835]
 [ 0.08163654  0.70521669]]
weights hidden output: [0.65906777 0.08337343]
output layer in: 0.4054651081073652
output : 0.5999999999998082
output error term: 4.6016523924670836e-14
weights hidden output: [0.65906777 0.08337343]
hidden layer output: [0.56649015 0.38513116]
Change in weights for hidden layer to output layer:
[2.34611169e-14 1.59501574e-14]
Change in weights for input layer to hidden layer:
[[ 3.35156565e-15  4.08832224e-16]
 [ 6.70313129e-16  8.17664447e-17]
 [-1.34062